###
#   File name : Combine_Seurat_and_TCR.R
#   Author    : Hyunjin Kim
#   Date      : Apr 2, 2020
#   Email     : hyunjin.kim@stjude.org
#   Purpose   : We have Seurat object from scRNA-Seq and want to combine scTCR-Seq data
#               generated by Cell Ranger VDJ to the object.
#
#   * Some of the codes here are from Jared Andrews' codes.
#     https://github.com/j-andrews7
#
#   Instruction
#               1. Source("Combine_Seurat_and_TCR.R")
#               2. Run the function "combineSeuratNTCR" - specify a vector of input directories and the output file path
#               3. The combined Seurat object will be generated in the output path
#
#   Example
#               > source("The_directory_of_Combine_Seurat_and_TCR.R/Combine_Seurat_and_TCR.R")
#               > dir_list <- list.dirs("C:/Users/hkim8/SJ/SJCAR19-05/SJCAR19-05_TCR/", recursive = FALSE)
#               > combineSeuratNTCR(Seurat_RObj_path="./data/JCC212_Px5.Robj",
#                                   TCR_data_dirs=dir_list,
#                                   outFilePath="./data/JCC212_Px5_TCR_combined.Robj")
###

combineSeuratNTCR <- function(Seurat_RObj_path="./data/JCC212_Px5.Robj",
                              TCR_data_dirs,
                              outFilePath="./data/JCC212_Px5_TCR_combined.Robj") {
  
  ### load library
  if(!require(Seurat, quietly = TRUE)) {
    install.packages("Seurat")
    require(Seurat, quietly = TRUE)
  }
  
  ### load the Seurat object and save the object name
  tmp_env <- new.env()
  load(Seurat_RObj_path, tmp_env)
  obj_name <- ls(tmp_env)
  assign("Seurat_Obj", get(obj_name, envir = tmp_env))
  rm(tmp_env)
  gc()
  
  ### for each TCR data combine them to the Seurat object
  tcr <- NULL
  for(i in 1:length(TCR_data_dirs)) {
    
    ### load filtered contig annotation data
    tcr_data <- read.csv(file = paste0(TCR_data_dirs[i], "/filtered_contig_annotations.csv"),
                         stringsAsFactors = FALSE, check.names = FALSE)
    
    ### load clonotype info data
    clono_data <- read.csv(file = paste0(TCR_data_dirs[i], "/clonotypes.csv"),
                           stringsAsFactors = FALSE, check.names = FALSE)
    
    ### Remove the -* at the end of each barcode.
    ### Subsets so only the first line of each barcode is kept,
    ### as each entry for given barcode will have same clonotype.
    tcr_data$barcode <- sapply(strsplit(tcr_data$barcode, split = "-", fixed = TRUE), function(x) x[1])
    tcr_data <- tcr_data[!duplicated(tcr_data$barcode), ]
    
    ### Slap the AA and NT sequences onto our original table by clonotype_id.
    ### * In the original code, the merge function was performed wrongly
    tcr_data <- merge(tcr_data, clono_data[, c("clonotype_id", "cdr3s_aa", "cdr3s_nt")],
                      by.x = "raw_clonotype_id", by.y = "clonotype_id", all.x = TRUE)
    
    ### only retain informative columns
    tcr_data <- tcr_data[,c("barcode", "raw_clonotype_id", "cdr3s_aa", "cdr3s_nt")]
    colnames(tcr_data)[2] <- "clonotype_id"
    
    ### add time info
    temp <- strsplit(basename(TCR_data_dirs[i]), split = "_", fixed = TRUE)[[1]][-c(1,2,3)]
    if(temp[1] == "PB" || temp[1] == "BM") {
      tcr_data$time <- temp[2]
      tcr_data$type <- temp[1]
    } else if(grepl("GMP", temp[1])) {
      tcr_data$time <- "GMP"
      tcr_data$type <- "GMP"
    } else if(temp[2] == "PB" || temp[2] == "BM") {
      tcr_data$time <- temp[1]
      tcr_data$type <- temp[2]
    } else {
      tcr_data$time <- temp[1]
      tcr_data$type <- "PB"
    }
    
    ### combine the TCR data for all the data
    if(is.null(tcr)) {
      tcr <- tcr_data
    } else {
      tcr <- rbind(tcr, tcr_data)
    }
    
  }
  
  ### attach the TCR info to the metadata of the Seurat object
  obj_colnames <- colnames(Seurat_Obj@meta.data)
  tcr_colnames <- colnames(tcr)
  Seurat_Obj@meta.data <- merge(Seurat_Obj@meta.data,
                                tcr,
                                by.x = c("GexCellShort", "Time", "Type"),
                                by.y = c("barcode", "time", "type"),
                                all.x = TRUE)
  Seurat_Obj@meta.data <- Seurat_Obj@meta.data[,c(obj_colnames, setdiff(tcr_colnames, c("barcode", "time", "type")))]
  rownames(Seurat_Obj@meta.data) <- Seurat_Obj@meta.data[,"GexCellFull"]
  
  ### change the object name to the original one
  assign(obj_name, Seurat_Obj)
  rm(Seurat_Obj)
  gc()
  
  ### save the combined Seurat object
  save(list = c(obj_name), file = outFilePath)
  
}
